# Generated by Django 4.1 on 2022-09-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300, null=True)),
                ('image_path', models.FileField(upload_to='bird_images/')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
