# Generated by Django 4.1 on 2022-09-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdSpecies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='image_path',
            field=models.ImageField(null=True, upload_to='bird_images/'),
        ),
    ]
