# Generated by Django 4.1 on 2022-09-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdSpecies', '0002_alter_species_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='bird_images/'),
        ),
    ]
